const P=['רועי','ענת','אמיתי','איילת','יהודית','מלאכי'];
const H=[['ראש השנה','2026-09-11','2026-09-13'],['יום כיפור','2026-09-20','2026-09-21'],['סוכות','2026-09-25','2026-10-02'],['שמחת תורה','2026-10-02','2026-10-03'],['פסח','2027-04-21','2027-04-28'],['שבועות','2027-06-10','2027-06-11']];
const U='https://mwfvziqmbkrjrnbbzqsf.supabase.co',K='sb_publishable_-uoZ_lp_4KejIKrXxanR7g_JMmbBG47';
const D=s=>new Date(s+'T12:00:00Z'),add=(d,n)=>{d=new Date(d);d.setUTCDate(d.getUTCDate()+n);return d},ymd=d=>d.toISOString().slice(0,10);
function make(){let a=[],d=D('2026-08-13'),z=D('2027-08-12');while(d<=z){a.push({id:'w-'+ymd(d),title:'שבת חגי',start:new Date(d),end:add(d,2)});d=add(d,7)}H.forEach(h=>a.push({id:'h-'+h[0]+h[1],title:h[0],start:D(h[1]),end:D(h[2])}));a.sort((x,y)=>x.start-y.start);let s=Object.fromEntries(P.map(x=>[x,{t:0,p:0,r:0}]));return a.map(e=>{let p=[...P].sort((a,b)=>s[a].t-s[b].t||s[a].p-s[b].p)[0];s[p].t++;s[p].p++;let r=P.filter(x=>x!==p).sort((a,b)=>s[a].t-s[b].t||s[a].r-s[b].r)[0];s[r].t++;s[r].r++;return {...e,op:p,od:r,pickup:p,dropoff:r}})}
const esc=s=>String(s).replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(',','\\,').replaceAll(';','\\;');
export default async function handler(req,res){let A=make();try{const r=await fetch(U+'/rest/v1/shabbat_hagai_overrides?select=*',{headers:{apikey:K}});const rows=await r.json();const O=Object.fromEntries(rows.map(x=>[x.event_id,x]));A.forEach(e=>{const o=O[e.id]||{};if(o.pickup_swapped&&o.pickup_replacement)e.pickup=o.pickup_replacement;if(o.dropoff_swapped&&o.dropoff_replacement)e.dropoff=o.dropoff_replacement})}catch(e){}
const who=decodeURIComponent(req.query.who||'הכול');const today=new Date();today.setUTCHours(0,0,0,0);A=A.filter(e=>e.end>=today&&(who==='הכול'||e.pickup===who||e.dropoff===who));
const f=d=>ymd(d).replaceAll('-','');const body='BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Shabbat Hagai//HE\r\nCALSCALE:GREGORIAN\r\nX-WR-CALNAME:'+esc(who==='הכול'?'שבת חגי':'שבת חגי - '+who)+'\r\nREFRESH-INTERVAL;VALUE=DURATION:PT6H\r\nX-PUBLISHED-TTL:PT6H\r\n'+A.map(e=>'BEGIN:VEVENT\r\nUID:'+e.id+'@shabbat-hagai.vercel.app\r\nDTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')+'\r\nDTSTART;VALUE=DATE:'+f(e.start)+'\r\nDTEND;VALUE=DATE:'+f(add(e.end,1))+'\r\nSUMMARY:'+esc(e.title+' ❤️')+'\r\nDESCRIPTION:'+esc('🏠 לוקח/ת: '+e.pickup+'\n🚗 מחזיר/ה: '+e.dropoff+'\nהוסטל רמת גן ↔ קרני שומרון')+'\r\nEND:VEVENT').join('\r\n')+'\r\nEND:VCALENDAR\r\n';
res.setHeader('Content-Type','text/calendar; charset=utf-8');res.setHeader('Cache-Control','public, max-age=300, s-maxage=300');res.status(200).send(body)}
